apiVersion: v1
kind: Deployment
metadata:
  name:  discord-boost-role-bot
  labels:
    name: discord-boost-role-bot
spec:
  selector:
    matchLabels:
      name:  discord-boost-role-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  discord-boost-role-bot
    spec:
      containers:
      - image:  192.168.1.175:5000/discord-boost-role-bot:latest
        name:  discord-boost-role-bot
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "100m"
            memory: "100M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        # ports:
        # - containerPort:  5000
        #   name:  discord-boost-role-bot
        volumeMounts:
          # Mount only the appsettings.json file from the configmap
          - name: boost-role-bot-config-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
          # Mount only the secrets.json file from the configmap
          - name: boost-role-bot-config-volume
            mountPath: /app/secrets.json
            subPath: secrets.json
      volumes:
        - name: boost-role-bot-config-volume
          configMap:
            name: boost-role-bot-config
            items:
              - key: appsettings.json
                path: appsettings.json
              - key: secrets.json
                path: secrets.json
          
      restartPolicy: Always
      imagePullPolicy: Always