apiVersion: apps/v1
kind: Deployment
metadata:
  name:  discord-boost-role-bot
  labels:
    name: discord-boost-role-bot
spec:
  selector:
    matchLabels:
      name:  discord-boost-role-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  discord-boost-role-bot
    spec:
      # Add affinity to schedule on an arm64 node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
                - amd64
      containers:
      - image:  192.168.1.175:5000/discord-boost-role:latest
        name:  discord-boost-role-bot
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "250M"
          limits:
            cpu: "500m"
            memory: "500M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        # ports:
        # - containerPort:  5000
        #   name:  discord-boost-role-bot
        volumeMounts:
          # Mount only the appsettings.json file from the configmap
          - name: boost-role-bot-appsettings-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
            readOnly: true
          # Mount only the secrets.json file from the secrets file map
          - name: boost-role-bot-secrets-volume
            mountPath: /app/secrets.json
            subPath: secrets.json
            readOnly: true
      volumes:
        - name: boost-role-bot-appsettings-volume
          configMap:
            name: boost-role-bot-config
            items:
              - key: appsettings.json
                path: appsettings.json
        - name: boost-role-bot-secrets-volume
          secret:
            secretName: boost-role-bot-secrets
            items:
              - key: secrets.json
                path: secrets.json
          
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
